### ISSUE TITLE
Suggest option to navigate to Openstreetmap

### ISSUE THREAD

**Issue by ppKrauss** [Andrew67/geo-handler#1]
Without association to an external execution, only redirects the coordinates. Example using `geo:-22.662,-48.635`, redirect to https://www.openstreetmap.org/#map=8/-22.662/-48.635

**Comment by Andrew67** [comment]
Hi @ppKrauss ,
Thank you for your interest in my project!
Unfortunately, this is a browser API limitation. Users will have to select the extension at least once from that dialog in order to associate it with the `geo:` URIs.
If this changes in the future please feel free to open a Pull Request or another Issue with the API information and I can integrate it into the extension.
